[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true


[[language]]
name = "ejs"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true
file-types = ["ejs"]
language-servers = ["vscode-html-language-server"]

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]
